---

language: python
python: "2.7"

env:
  matrix:
     - ANSIBLE_VERSION="2.3.1.0"

install:
  - pip install ansible=="$ANSIBLE_VERSION"

script:
  - echo localhost > inventory
  # wait for load to drop
  - sleep 100
  # Syntax check
  - ansible-playbook -i inventory tests/playbook.yml --syntax-check

  - time ansible-playbook -i inventory tests/playbook.yml --connection=local --tags hash
  - time ansible-playbook -i inventory tests/playbook.yml --connection=local --tags individual

